spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
#    generate-unique-name: false # 임의 명칭 생성 여부(true - 랜덤 생성, false - 명칭 고정)

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
     # show_sql: true
         format_sql: true
#  h2:
#    console:
#      enabled: true # H2 콘솔 사용 여부

logging:
  level:
   org.hibernate.SQL: debug
   org.hibernate.orm.jdbc.bind: trace
# org.hibernate.type: trace #스프링 부트 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6
#server:
#  port: 8082
