spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop
#    url: jdbc:h2:mem:test
    #테스트는 케이스 격리된 환경에서 실행하고, 끝나면 데이터를 초기화하는 것이 좋다.
    #그런 면에서 메모리 DB를 사용하는 것이 가장 이상적이다.
    #추가로 테스트 케이스를 위한 스프링 환경과,일반적으로 애플리케이션을 실행하는 환경은 보통 다르므로 설정 파일을 다르게 사용하자.
#    username: sa
#    password: 1234
#    driver-class-name: org.h2.Driver
#    generate-unique-name: false # 임의 명칭 생성 여부(true - 랜덤 생성, false - 명칭 고정)

#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#     # show_sql: true
#         format_sql: true
#
  #스프링 부트는 datasource 설정이 없으면, 기본적을 메모리 DB를 사용하고, driver-class도 현재 등록된
  #라이브러를 보고 찾아준다. 추가로 ddl-auto 도 create-drop 모드로 동작한다. 따라서 데이터소스나,
  #JPA 관련된 별도의 추가 설정을 하지 않아도 된다


#  h2:
#    console:
#      enabled: true # H2 콘솔 사용 여부

logging:
  level:
   org.hibernate.SQL: debug
   org.hibernate.orm.jdbc.bind: trace
# org.hibernate.type: trace #스프링 부트 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6
#server:
#  port: 8082
